# Generated by Django 5.2.7 on 2026-04-17 17:58

import biblioteca.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0005_alter_evaluacion_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, help_text='Formatos permitidos: Documentos, Diseños (AI, PSD), Imágenes y Video corto.', upload_to=biblioteca.models.generar_ruta_apunte, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'csv', 'png', 'jpg', 'jpeg', 'svg', 'tiff', 'psd', 'ai', 'indd', 'mp4', 'mov', 'gif', 'zip', 'rar'])])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuntes', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuntes', to='notas.materia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
