# Generated by Django 5.2 on 2026-04-16 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='archivo',
            field=models.FileField(blank=True, help_text='Formatos permitidos: Documentos, Diseños (AI, PSD), Imágenes y Video corto.', upload_to='evaluaciones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'csv', 'png', 'jpg', 'jpeg', 'svg', 'tiff', 'psd', 'ai', 'indd', 'mp4', 'mov', 'gif', 'zip', 'rar'])]),
        ),
    ]
