# Generated by Django 5.2.7 on 2026-04-17 17:58

import django.core.validators
import notas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_evaluacion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='archivo',
            field=models.FileField(blank=True, help_text='Formatos permitidos: Documentos, Diseños (AI, PSD), Imágenes y Video corto.', upload_to=notas.models.generar_ruta_evaluacion, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'csv', 'png', 'jpg', 'jpeg', 'svg', 'tiff', 'psd', 'ai', 'indd', 'mp4', 'mov', 'gif', 'zip', 'rar'])]),
        ),
    ]
